In [54]:
import torch
import torch.nn.functional as F

In [2]:
B, T, C = 4, 8, 2 # Batch, Time, Channels
x = torch.randn(B, T, C)
x.shape

torch.Size([4, 8, 2])

In [7]:
xbow = torch.zeros((B, T, C))
for b in range(B):
    for t in range(T):
        xprev = x[b, :t+1]
        xbow[b, t] = torch.mean(xprev, 0)

In [10]:
x[0]

tensor([[ 0.5609,  0.2685],
        [-1.4828, -0.5269],
        [ 0.1231, -1.0716],
        [-1.7261,  0.0368],
        [-1.2870,  0.2794],
        [-0.4768, -0.4708],
        [-0.4424, -0.5906],
        [ 0.2525,  0.2796]])

In [9]:
xbow[0]

tensor([[ 0.5609,  0.2685],
        [-0.4610, -0.1292],
        [-0.2663, -0.4433],
        [-0.6312, -0.3233],
        [-0.7624, -0.2028],
        [-0.7148, -0.2474],
        [-0.6759, -0.2965],
        [-0.5598, -0.2244]])

In [15]:
torch.manual_seed(42)

a = torch.ones(3,3)
b = torch.randint(0, 10, (3,2)).float()
c = a @ b

print("a: \n", a)
print("b: \n", b)
print("c: \n", c)

a: 
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
b: 
 tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
c: 
 tensor([[14., 16.],
        [14., 16.],
        [14., 16.]])


In [16]:
torch.tril(a)

tensor([[1., 0., 0.],
        [1., 1., 0.],
        [1., 1., 1.]])

tensor([1., 2., 3.])

In [27]:
tri = torch.tril(a)
f = torch.Tensor([range(3)]) + 1
tri / f.T

tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])

In [41]:
torch.sum(tri, dim=1, keepdim=True)

tensor([[1.],
        [2.],
        [3.]])

In [42]:
w = torch.tril(torch.ones(T, T))
w = w / w.sum(1, keepdim=True)

In [43]:
w

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000, 0.0000],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.0000, 0.0000],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.0000],
        [0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250]])

In [44]:
xbow2 = w @ x

In [47]:
w.shape, x.shape

(torch.Size([8, 8]), torch.Size([4, 8, 2]))

In [55]:
w = torch.tril(torch.ones(T, T))
w = w.masked_fill(w == 0, float('-inf'))
w = F.softmax(w, dim=-1)
xbow3 = w @ x
torch.allclose(xbow, xbow3)

True

In [64]:
w = torch.tril(torch.ones(T, T))
w = w.masked_fill(w == 0, float('-inf'))
F.softmax(w, dim=-1)

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000, 0.0000],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.0000, 0.0000],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.0000],
        [0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250]])